title: zzlzk's IQ is 0.
subtitle: Naivest OIer.
description: Nothing is impossible.
author: zzlzk
language: zh-Hans #en
date_format: '%Y-%m-%d'

url:
baseurl:
permalink: pretty

paginate: 7
paginate_path: "/page:num/"
archive:
  paginate: 7
  paginate_path: "/page:num/"
category:
  paginate: 7
  paginate_path: "/page:num/"
tag:
  paginate: 7
  paginate_path: "/page:num/"


exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", "Gemfile", "Gemfile.lock", "README_en.md"]

highlighter: rouge

markdown: kramdown
kramdown:
    input: GFM

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true

feed:
  path: atom.xml

plugins:
 - jemoji
 - jekyll-sitemap
 - jekyll-feed

favicon: /assets/favicon.ico

keywords: "Jekyll, NexT"

rss:

since: 2017

authoricon: toggle-on

copyright: true

canonical: true

seo: false

index_with_subtitle: false

local_search:
  enable: true

menu:
  home: /
  categories: /categories/
  about: /about/
  archives: /archives/
  tags: /tags/

menu_icons:
  enable: true
  home: home
  about: wheelchair-alt
  categories: th
  tags: tags
  archives: archive
  search: search

scheme: Pisces # Mist | Pisces | Muse

font:
  enable: true

  host:

  global:
    external: true
    family: Microsoft YaHei #Lato

  headings:
    external: true
    family: Microsoft YaHei

  posts:
    external: true
    family: Microsoft YaHei

  logo:
    external: true
    family: Microsoft YaHei
    size:

  codes:
    external: true
    family: Courier_new
    size:

social:
  GitHub: https://github.com/zzlzk
  Luogu: https://www.luogu.org/space/show?uid=37700
  BZOJ: http://www.lydsy.com/JudgeOnline/userinfo.php?user=xjjppm
  知乎: https://www.zhihu.com/people/zzlzk/activities

social_icons:
  enable: true
  GitHub: github
  Luogu: code
  BZOJ: bold
  知乎: bath

avatar: /assets/images/avatar.gif

toc:
  enable: true
  number: true
  wrap: false

creative_commons: by-nc-sa

sidebar:
  position: left #right
  display: post #always | hide | remove
  offset: 12
  offset_float: 0
  b2t: true
  scrollpercent: false

links_title: Friends
links:
  ZlycerQan: http://zlycerqan.xyz/

scroll_to_more: true

save_scroll: false

excerpt_description: true

auto_excerpt:
  enable: false
  length: 150

post_meta:
  item_text: true
  created_at: true
  updated_at: false
  categories: true

post_wordcount:
  item_text: true
  wordcount: false
  min2read: false
  separated_meta: true

post_copyright:
  enable: true
  license: CC BY-NC-SA 3.0
  license_url: https://creativecommons.org/licenses/by-nc-sa/3.0/



# ---------------------------------------------------------------
# Misc Theme Settings
# ---------------------------------------------------------------

# Custom Logo.
# !!Only available for Default Scheme currently.
# Options:
#   enabled: [true/false] - Replace with specific image
#   image: url-of-image   - Images's url
custom_logo:
  enabled: false
  image:

highlight_theme: normal # normal | night | night eighties | night blue | night bright

mathjax:
  enable: true
  per_page: true
  cdn: //cdn.bootcss.com/mathjax/2.7.1/latest.js?config=TeX-AMS-MML_HTMLorMML

baidu_analytics: d58521b3f4eeed6f97aefb01c566bf6d

baidu_push: true

livere_uid: MTAyMC8zMjQwNC84OTY1

#can't modify

use_motion: true
fancybox: true
pace: false
#pace-theme-big-counter
#pace-theme-bounce
#pace-theme-barber-shop
#pace-theme-center-atom
#pace-theme-center-circle
#pace-theme-center-radar
#pace-theme-center-simple
#pace-theme-corner-indicator
#pace-theme-fill-left
#pace-theme-flash
#pace-theme-loading-bar
#pace-theme-mac-osx
#pace-theme-minimal
pace_theme: pace-theme-minimal

canvas_nest: true
three_waves: false
canvas_lines: false
canvas_sphere: false
canvas_ribbon: false

vendors:
  _internal: assets/lib
  jquery:
  fancybox:
  fancybox_css:
  fastclick:
  lazyload:
  velocity:
  velocity_ui:
  ua_parser:
  fontawesome:
  algolia_instant_js:
  algolia_instant_css:
  pace:
  pace_css:
  canvas_nest:
  three:
  three_waves:
  canvas_lines:
  canvas_sphere:
  canvas_ribbon:
  han:

css: assets/css
js: assets/js
images: assets/images

version: 5.1.1
